### ISSUE TITLE
where is the python code of this paper？

### ISSUE THREAD

**Issue by niutyut** [saref/multilevel-balance#1]
hello，i am reading multilevel-balance paper ，but i can not find your data and code。where is it？thank you!

**Comment by saref** [comment]
Hello,

Thank you for your comment.

We expect the paper to be published in the next couple of weeks. Both the data and the code will be released upon online publication of the paper. The code will be here on GitHub (https://github.com/saref/multilevel-balance) and the data will be on FigShare (https://doi.org/10.6084/m9.figshare.12152628).

-Samin
